SIM ?= icarus
TOPLEVEL_LANG ?= verilog

# RTL source files
VERILOG_SOURCES += $(PWD)/../rtl/cgra_pe.v
VERILOG_SOURCES += $(PWD)/../rtl/cgra_mesh.v
VERILOG_SOURCES += $(PWD)/../rtl/cgra_sequencer.v
VERILOG_SOURCES += $(PWD)/../rtl/cgra_top.v

# Top-level module name inside RTL
TOPLEVEL = cgra_top

# Name of the python testbench file (without .py)
MODULE = tb_cgra_driver

include $(shell cocotb-config --makefiles)/Makefile.sim
