SIM ?= icarus
TOPLEVEL_LANG ?= verilog

# RTL source files
VERILOG_SOURCES += $(PWD)/../rtl/mx_pwl_exp.v
VERILOG_SOURCES += $(PWD)/../rtl/mx_pwl_recip.v
VERILOG_SOURCES += $(PWD)/../rtl/mx_softmax_unit.v

# Top-level module name inside RTL
TOPLEVEL = mx_softmax_unit

# Name of the python testbench file (without .py)
MODULE = tb_mx_softmax_unit

include $(shell cocotb-config --makefiles)/Makefile.sim
